# Generated by Django 3.0.4 on 2020-05-07 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_day_1', models.CharField(max_length=50)),
                ('company_start_time_1', models.IntegerField()),
                ('company_end_time_1', models.IntegerField()),
                ('company_studio_1', models.CharField(max_length=50)),
                ('company_day_2', models.CharField(max_length=50)),
                ('company_start_time_2', models.IntegerField()),
                ('company_end_time_2', models.IntegerField()),
                ('company_studio_2', models.CharField(max_length=50)),
                ('company_day_3', models.CharField(max_length=50)),
                ('company_start_time_3', models.IntegerField()),
                ('company_end_time_3', models.IntegerField()),
                ('company_studio_3', models.CharField(max_length=50)),
                ('num_reho', models.IntegerField()),
                ('company_size', models.IntegerField()),
                ('bloomberg_rank', models.IntegerField(default=0)),
                ('dillon_dance_rank', models.IntegerField(default=0)),
                ('dillon_mar_rank', models.IntegerField(default=0)),
                ('dillon_mpr_rank', models.IntegerField(default=0)),
                ('murphy_rank', models.IntegerField(default=0)),
                ('ns_rank', models.IntegerField(default=0)),
                ('ns_warmup_rank', models.IntegerField(default=0)),
                ('ns_theatre_rank', models.IntegerField(default=0)),
                ('whitman_rank', models.IntegerField(default=0)),
                ('wilcox_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_id', models.IntegerField(default=0, unique=True)),
                ('showtime', models.DateField()),
                ('contact', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=50)),
                ('studio_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.IntegerField(default=0)),
                ('num_reho', models.IntegerField()),
                ('member_size', models.IntegerField()),
                ('submit_date', models.DateField(default=datetime.date.today)),
                ('rank_1', models.IntegerField(default=0)),
                ('rank_2', models.IntegerField(default=0)),
                ('rank_3', models.IntegerField(default=0)),
                ('rank_4', models.IntegerField(default=0)),
                ('rank_5', models.IntegerField(default=0)),
                ('rank_6', models.IntegerField(default=0)),
                ('rank_7', models.IntegerField(default=0)),
                ('rank_8', models.IntegerField(default=0)),
                ('rank_9', models.IntegerField(default=0)),
                ('rank_10', models.IntegerField(default=0)),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('company_choice_num', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('company_day', models.CharField(max_length=50)),
                ('company_start_time', models.IntegerField()),
                ('company_end_time', models.IntegerField()),
                ('submit_date', models.DateField(default=datetime.date.today)),
                ('company_studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Studio', to_field='studio_id')),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('from_alg', models.IntegerField(default=0)),
                ('user_netid', models.CharField(max_length=50)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('week_day', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id')),
                ('studio_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Studio', to_field='studio_id')),
            ],
        ),
    ]
