# Generated by Django 3.0.4 on 2020-05-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_id', models.IntegerField(default=0, unique=True)),
                ('showtime', models.DateField()),
                ('contact', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=50)),
                ('studio_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.IntegerField(default=0)),
                ('num_reho', models.IntegerField()),
                ('member_size', models.IntegerField()),
                ('submit_date', models.CharField(max_length=50, unique=True)),
                ('rank_1', models.IntegerField(default=0)),
                ('rank_2', models.IntegerField(default=0)),
                ('rank_3', models.IntegerField(default=0)),
                ('rank_4', models.IntegerField(default=0)),
                ('rank_5', models.IntegerField(default=0)),
                ('rank_6', models.IntegerField(default=0)),
                ('rank_7', models.IntegerField(default=0)),
                ('rank_8', models.IntegerField(default=0)),
                ('rank_9', models.IntegerField(default=0)),
                ('rank_10', models.IntegerField(default=0)),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_choice_num', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('company_day', models.CharField(max_length=50)),
                ('company_start_time', models.IntegerField()),
                ('company_end_time', models.IntegerField()),
                ('submit_date', models.CharField(max_length=50, unique=True)),
                ('company_studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Studio', to_field='studio_id')),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id')),
                ('request_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.RehearsalRequest', to_field='request_id', verbose_name='Rehearsals')),
            ],
        ),
    ]
