# Generated by Django 3.0.5 on 2020-04-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_day_1', models.CharField(max_length=50)),
                ('company_start_time_1', models.IntegerField()),
                ('company_end_time_1', models.IntegerField()),
                ('company_studio_1', models.CharField(max_length=50)),
                ('company_day_2', models.CharField(max_length=50)),
                ('company_start_time_2', models.IntegerField()),
                ('company_end_time_2', models.IntegerField()),
                ('company_studio_2', models.CharField(max_length=50)),
                ('company_day_3', models.CharField(max_length=50)),
                ('company_start_time_3', models.IntegerField()),
                ('company_end_time_3', models.IntegerField()),
                ('company_studio_3', models.CharField(max_length=50)),
                ('num_reho', models.IntegerField()),
                ('company_size', models.IntegerField()),
                ('rank_1', models.CharField(default='wilcox', max_length=50)),
                ('rank_2', models.CharField(max_length=50)),
                ('rank_3', models.CharField(max_length=50)),
                ('rank_4', models.CharField(max_length=50)),
                ('rank_5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('week_day', models.IntegerField()),
                ('booking_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('showtime', models.DateField()),
                ('contact', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
