# Generated by Django 3.0.4 on 2020-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_netid',
            field=models.CharField(default='hc20', max_length=50),
            preserve_default=False,
        ),
    ]
