# Generated by Django 3.0.4 on 2020-05-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrequest',
            name='submit_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.IntegerField(default=0),
        ),

    ]
