# Generated by Django 3.0.4 on 2020-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_day', models.CharField(max_length=50)),
                ('company_start_time', models.IntegerField()),
                ('company_end_time', models.IntegerField()),
                ('company_studio', models.CharField(max_length=50)),
                ('rank_1', models.CharField(max_length=50)),
                ('rank_2', models.CharField(max_length=50)),
                ('rank_3', models.CharField(max_length=50)),
                ('rank_4', models.CharField(max_length=50)),
                ('rank_5', models.CharField(max_length=50)),
                ('num_reho', models.IntegerField()),
                ('num_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
