# Generated by Django 3.0.4 on 2020-04-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0002_booking_user_netid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_netid',
        ),
    ]
