# Generated by Django 3.0.4 on 2020-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0002_adrequest_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_day_1', models.CharField(max_length=50)),
                ('company_start_time_1', models.IntegerField()),
                ('company_end_time_1', models.IntegerField()),
                ('company_studio_1', models.CharField(max_length=50)),
                ('company_day_2', models.CharField(max_length=50)),
                ('company_start_time_2', models.IntegerField()),
                ('company_end_time_2', models.IntegerField()),
                ('company_studio_2', models.CharField(max_length=50)),
                ('company_day_3', models.CharField(max_length=50)),
                ('company_start_time_3', models.IntegerField()),
                ('company_end_time_3', models.IntegerField()),
                ('company_studio_3', models.CharField(max_length=50)),
                ('rank_1', models.CharField(max_length=50)),
                ('rank_2', models.CharField(max_length=50)),
                ('rank_3', models.CharField(max_length=50)),
                ('rank_4', models.CharField(max_length=50)),
                ('rank_5', models.CharField(max_length=50)),
                ('num_reho', models.IntegerField()),
                ('num_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_day', models.CharField(max_length=50)),
                ('company_start_time', models.IntegerField()),
                ('company_end_time', models.IntegerField()),
                ('studio', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ADRequest',
        ),
    ]
