# Generated by Django 3.0.4 on 2020-04-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0003_auto_20200411_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADR',
            new_name='ADRequest',
        ),
    ]
