# Generated by Django 3.0.4 on 2020-04-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0004_auto_20200411_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('showtime', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('booking_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyChoice',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RenameField(
            model_name='adrequest',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='adrequest',
            old_name='num_members',
            new_name='company_size',
        ),
    ]
