# Generated by Django 3.0.4 on 2020-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0004_booking_user_netid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_alg',
            field=models.IntegerField(default=0),
        ),
    ]
