# Generated by Django 3.0.4 on 2020-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0005_booking_from_alg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='company_id',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='company_name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='name',
            new_name='studio_name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
