# Generated by Django 3.0.5 on 2020-05-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0006_auto_20200505_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('company_choice_num', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('company_day', models.CharField(max_length=50)),
                ('company_start_time', models.IntegerField()),
                ('company_end_time', models.IntegerField()),
                ('company_studio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResearsalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('num_reho', models.IntegerField()),
                ('member_size', models.IntegerField()),
                ('bloomberg_rank', models.IntegerField(default=0)),
                ('dillon_dance_rank', models.IntegerField(default=0)),
                ('dillon_mar_rank', models.IntegerField(default=0)),
                ('dillon_mpr_rank', models.IntegerField(default=0)),
                ('murphy_rank', models.IntegerField(default=0)),
                ('ns_rank', models.IntegerField(default=0)),
                ('ns_warmup_rank', models.IntegerField(default=0)),
                ('ns_theatre_rank', models.IntegerField(default=0)),
                ('whitman_rank', models.IntegerField(default=0)),
                ('wilcox_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='studio',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
