# Generated by Django 3.0.4 on 2020-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0007_auto_20200412_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
