# Generated by Django 3.0.5 on 2020-05-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0007_auto_20200505_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyRequest',
        ),
        migrations.DeleteModel(
            name='ResearsalRequest',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_id',
            field=models.IntegerField(unique=True),
        ),
    ]
