# Generated by Django 3.0.4 on 2020-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0008_auto_20200412_2159'),
    ]

    operations = [
         migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
