# Generated by Django 3.0.5 on 2020-05-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0008_auto_20200505_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='studio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Studio', to_field='studio_id'),
        ),
    ]
