# Generated by Django 3.0.4 on 2020-04-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0009_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
