# Generated by Django 3.0.5 on 2020-05-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0009_auto_20200505_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(unique=True)),
                ('company_choice_num', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('company_day', models.CharField(max_length=50)),
                ('company_start_time', models.IntegerField()),
                ('company_end_time', models.IntegerField()),
                ('company_studio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Studio', to_field='studio_id')),
            ],
        ),
    ]
