# Generated by Django 3.0.5 on 2020-05-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0010_companyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearsalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.IntegerField(default=0)),
                ('num_reho', models.IntegerField()),
                ('member_size', models.IntegerField()),
                ('rank_1', models.IntegerField(default=0)),
                ('rank_2', models.IntegerField(default=0)),
                ('rank_3', models.IntegerField(default=0)),
                ('rank_4', models.IntegerField(default=0)),
                ('rank_5', models.IntegerField(default=0)),
                ('rank_6', models.IntegerField(default=0)),
                ('rank_7', models.IntegerField(default=0)),
                ('rank_8', models.IntegerField(default=0)),
                ('rank_9', models.IntegerField(default=0)),
                ('rank_10', models.IntegerField(default=0)),
                ('request_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.CompanyRequest', verbose_name='Rehearsals')),
            ],
        ),
    ]
