# Generated by Django 3.0.4 on 2020-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0010_auto_20200414_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
