# Generated by Django 3.0.4 on 2020-04-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0011_auto_20200414_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='week_day',
        ),
    ]
