# Generated by Django 3.0.5 on 2020-05-06 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0011_researsalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrequest',
            name='submit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='researsalrequest',
            name='submit_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
