# Generated by Django 3.0.4 on 2020-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0012_auto_20200414_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='week_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
