# Generated by Django 3.0.4 on 2020-05-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0012_auto_20200505_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrequest',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id'),
        ),
        migrations.AddField(
            model_name='researsalrequest',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pacApp.Group', to_field='group_id'),
        ),
    ]
