# Generated by Django 3.0.4 on 2020-05-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0013_auto_20200505_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearsalRequest',
            new_name='RehearsalRequest',
        ),
    ]
