# Generated by Django 3.0.4 on 2020-04-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0006_auto_20200412_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
