# Generated by Django 3.0.4 on 2020-04-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0013_auto_20200414_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
