# Generated by Django 3.0.4 on 2020-04-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacApp', '0015_auto_20200416_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrequest',
            name='rank_1',
            field=models.CharField(default='wilcox', max_length=50),
        ),
    ]
